[mypy]

python_version = 3.6

# Do not error on imported files since all imported files may not be mypy clean.
follow_imports = silent

# Do not error if imports are not found.
# This can be a problem with standalone scripts and relative imports.
# This will limit effectiveness but avoids mypy complaining about running code.
ignore_missing_imports = True

# Disallows calling functions without type annotations
# from functions with type annotations.
disallow_untyped_calls = True

# Disallows defining functions without type annotations or
# with incomplete type annotations.
disallow_untyped_defs = True

# Disallows defining functions with incomplete type annotations.
disallow_incomplete_defs = True

# Reports an error whenever a function with type annotations is decorated
# with a decorator without annotations.
disallow_untyped_decorators = True

# Disallows usage of generic types that do not specify explicit type parameters.
disallow_any_generics = True

# Disallows subclassing a value of type Any.
disallow_subclassing_any = True

# Shows a warning when returning a value with type Any from a function
# declared with a non- Any return type.
warn_return_any = True
